### ISSUE TITLE
Caught exceptions reading in a EDS file

### ISSUE THREAD

**Issue by soul4soul** [robincornelius/libedssharp#90]
When I open an EDS file a dialog window appears named "warning" with the following exceptions. Attached is the EDS file which causes these errors. 

From a quick overview it looks like the device info vendor name is not being read in as the text box is empty in the GUI.  Perhaps this is one of the fields which causes an ArgumentOutOfRange exception.

[test.txt](https://github.com/robincornelius/libedssharp/files/1092983/test.txt)

```
Error parsing node id  nodes, System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToUInt32(String value, Int32 fromBase)
   at libEDSsharp.EDSsharp.GetNodeID(String input, Boolean& nodeidpresent) in E:\libedssharp-master\libEDSsharp\eds.cs:line 1479

Error parsing node id  nodes, System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToUInt32(String value, Int32 fromBase)
   at libEDSsharp.EDSsharp.GetNodeID(String input, Boolean& nodeidpresent) in E:\libedssharp-master\libEDSsharp\eds.cs:line 1479

Error parsing node id  nodes, System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToUInt32(String value, Int32 fromBase)
   at libEDSsharp.EDSsharp.GetNodeID(String input, Boolean& nodeidpresent) in E:\libedssharp-master\libEDSsharp\eds.cs:line 1479

Error parsing node id  nodes, System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToUInt32(String value, Int32 fromBase)
   at libEDSsharp.EDSsharp.GetNodeID(String input, Boolean& nodeidpresent) in E:\libedssharp-master\libEDSsharp\eds.cs:line 1479

Error parsing node id  nodes, System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToUInt32(String value, Int32 fromBase)
   at libEDSsharp.EDSsharp.GetNodeID(String input, Boolean& nodeidpresent) in E:\libedssharp-master\libEDSsharp\eds.cs:line 1479

Error parsing node id  nodes, System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToUInt32(String value, Int32 fromBase)
   at libEDSsharp.EDSsharp.GetNodeID(String input, Boolean& nodeidpresent) in E:\libedssharp-master\libEDSsharp\eds.cs:line 1479

Error parsing node id  nodes, System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToUInt32(String value, Int32 fromBase)
   at libEDSsharp.EDSsharp.GetNodeID(String input, Boolean& nodeidpresent) in E:\libedssharp-master\libEDSsharp\eds.cs:line 1479

Error parsing node id  nodes, System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToUInt32(String value, Int32 fromBase)
   at libEDSsharp.EDSsharp.GetNodeID(String input, Boolean& nodeidpresent) in E:\libedssharp-master\libEDSsharp\eds.cs:line 1479
```

**Comment by robincornelius** [comment]
Vendor name is broken in the master branch for some reason, i think it because in your example you use vendorname and not VendorName. The xdd branch correctly does not care about case, where as the master branch did. 

The crash for both #90 and #91 was caused by some empty strings, they were tested for null but not for "" 

I've put a patch on both branches but xdd is really the more interesting branch now as it has a number of improvement and bug fixes which will allow it to read more of the less common eds outputs with compactsubobj and compactpdo etc
